
project_id = "jorbqjareswzdrsmepbv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[analytics]
enabled = false

[vector]
enabled = true

# Konfiguracja funkcji webhooka Stripe (bez JWT weryfikacji)
[functions.stripe-webhook]
verify_jwt = false

# Konfiguracja funkcji stripe-checkout (z JWT weryfikacją)
[functions.stripe-checkout]
verify_jwt = true
