
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "jorbqjareswzdrsmepbv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
immutable_file_backup = true

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
flexurls_port = 54325

[auth]
enabled = true
site_url = "http://localhost:3000"
# Additional redirect URLs allowed for OAuth providers
additional_redirect_urls = ["https://localhost:3000", "http://localhost:5173", "http://127.0.0.1", "http://127.0.0.1:54323/auth/v1/callback", "https://jorbqjareswzdrsmepbv.supabase.co"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions]
enabled = true
port = 54326

[functions.posthook-agent]
verify_jwt = false

[functions.postscript-agent]
verify_jwt = false

[functions.ai-agents]
verify_jwt = false

[functions.compress-text]
verify_jwt = false

[functions.check-session-details]
verify_jwt = false

[functions.check-subscription-status]
verify_jwt = false

[functions.generate-email]
verify_jwt = false

[functions.generate-email-content]
verify_jwt = false

[functions.generate-script]
verify_jwt = false

[functions.narrative-blueprint]
verify_jwt = false

[functions.generate-subject-lines]
verify_jwt = false

[functions.subscription-details]
verify_jwt = false

[functions.ui-cleaner]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.verify-payment-session]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.database-setup]
verify_jwt = false

[analytics]
enabled = false
port = 54327
vector_port = 54328
