
project_id = "jorbqjareswzdrsmepbv"

[functions.stripe-webhook]
verify_jwt = false

[functions.postscript-agent]
verify_jwt = false

[functions.posthook-agent]
verify_jwt = false

[functions.social-intro-agent]
verify_jwt = false

[functions.social-post-agent]
verify_jwt = false
