
project_id = "jorbqjareswzdrsmepbv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[analytics]
enabled = true

[vector]
enabled = true

[edge_functions]
[edge_functions.social-hook-agent]
verify_jwt = true

[edge_functions.social-content-agent]
verify_jwt = true

[edge_functions.generate-script]
verify_jwt = true

[edge_functions.generate-subject-lines]
verify_jwt = true
