
# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "jorbqjareswzdrsmepbv"

[functions.stripe-webhook]
verify_jwt = false

[functions.ai-agents/posthook-agent]
verify_jwt = true

[functions.ai-agents/postscript-agent]
verify_jwt = true
