
# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "jorbqjareswzdrsmepbv"

[functions.stripe-webhook]
verify_jwt = false

[functions.check-subscription-status]
verify_jwt = true

[functions.postscript-agent]
verify_jwt = false

[functions.posthook-agent]
verify_jwt = false

[functions.social-hook-agent]
verify_jwt = true

[functions.social-content-agent]
verify_jwt = true
