
[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Update the Stripe checkout redirect to be more explicit and handle POST properly
[[redirects]]
  from = "/.netlify/functions/stripe-checkout"
  to = "/.netlify/functions/stripe-checkout"
  status = 200
  force = true
  methods = "POST,OPTIONS"
  headers = { Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "POST,OPTIONS", Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With" }
