
[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Make Stripe checkout function explicitly handle all methods with better CORS
[[redirects]]
  from = "/.netlify/functions/stripe-checkout"
  to = "/.netlify/functions/stripe-checkout"
  status = 200
  force = true
  methods = "GET,POST,OPTIONS"
  headers = { Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET,POST,OPTIONS", Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, apikey, X-Client-Info, Cache-Control, Pragma, Expires, X-Timestamp, X-Random" }

# Handle CORS for Supabase requests
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Accept, Authorization, apikey, X-Client-Info, Cache-Control, Pragma, Expires, X-No-Cache, X-Cache-Buster, X-Timestamp, X-Random"
    Access-Control-Max-Age = "86400"
